[package]
name = "ra_duplicate_finder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
sha256 = "1.0.3"
num_cpus = "1.13.1"
threadpool = "1.8.1"